version: "3"
services:
  cassandra:
    image: cassandra
  redis:
    image: redis
  web:
    image: rickyrb/pedidosga
    ports:
      - 8080:8080
    links: 
      - redis:redis
      - cassandra:cassandra
    environment: 
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: 
      - cassandra
      - redis
