spring.profiles.active: dev

---

spring:
    profiles: dev
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: localhost
            port: 9042
    redis:
        host: localhost
        port: 6379

---

spring:
    profiles: docker
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379

---

spring:
    profiles: prod
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379
