spring.profiles.active: dev

spring:
    cache:
        type: redis
        redis.time-to-live: 60000
    mail:
        host: email-smtp.us-east-1.amazonaws.com
        username: DEZh2kkX3khf2RATqZEerCBORQ+eZ9eoR31FhrmRrIL3OT0s8oxQAL+czTQdOn41/w==
        password: DGrytSK8hF0Xs0kbUTcS/OETqSkXQlzRHd4MrkxdUN1xXIGHgdNENCjzGrHDdKPS9WeIGVCf5yu7UW8KA6SMyi4oF/MICDuaug==
        properties:
            mail:
                transport.protocol: smtp
                smtp:
                    port: 587
                    auth: true
                    starttls:
                        enable: true
                        required: true


pedidosga:
    aws:
        cognitoGroupId: us-east-1_CVePKGhTu
        accessKey: DDSCD4ufOznrUq6IvzQ/lis8b4pibmuTI7AAVLGhWxwtuoD9vw2/hl2AwL7n71yWPA==
        secretKey: DMnEOMCiztJ79DLqJZWOcZp4au3hjrDx9nVzNX4wMnYrR3/kLRtyxVbTg2QBVnrrCIUKuAtFO932W6ilVNqzJRl872kA

---

spring:
    profiles: dev
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: localhost
            port: 9042
    redis:
        host: localhost
        port: 6379
pedidosga:
    urlApiProductos: https://fvwzxk56cg.execute-api.us-east-1.amazonaws.com/mock/productos/{idProducto}

---

spring:
    profiles: docker
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379
logging:
    file: app/pedidosga.log
    max-size: 2MB
    max-history: 5
pedidosga:
    urlApiProductos: https://jsc2p92uk1.execute-api.us-east-1.amazonaws.com/v1/catalogo/productos/{idProducto}

---

spring:
    profiles: prod
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379
logging:
    file: app/logs/pedidosga.log
    max-size: 10MB
    max-history: 5
pedidosga:
    urlApiProductos: http://catalogoga:4000/catalogo/productos/{idProducto}
