spring.profiles.active: dev
spring.cache.type: redis
spring.cache.redis.time-to-live: 60000

pedidosga.awsCognitoGroupId: us-east-1_CVePKGhTu
pedidosga.awsAccessKey: yAVSrZiMimn8pFSFAlli_lje1qxSnmL_aoxCfSuMhkQ
pedidosga.awsSecretKey: 9pITKY-ng4PEaEX7GtUqcdk6L8sIIKMSmtzKt3haSU3hbPgIt-xz4TrMGHR8n5zu

---

spring:
    profiles: dev
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: localhost
            port: 9042
    redis:
        host: localhost
        port: 6379
pedidosga:
    urlApiProductos: https://fvwzxk56cg.execute-api.us-east-1.amazonaws.com/mock/productos/{idProducto}

---

spring:
    profiles: docker
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379
logging:
    file: app/pedidosga.log
    max-size: 2MB
    max-history: 5
pedidosga:
    urlApiProductos: https://fvwzxk56cg.execute-api.us-east-1.amazonaws.com/mock/productos/{idProducto}

---

spring:
    profiles: prod
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: cassandra
            port: 9042
    redis:
        host: redis
        port: 6379
logging:
    file: app/logs/pedidosga.log
    max-size: 10MB
    max-history: 5
pedidosga:
    urlApiProductos: https://fvwzxk56cg.execute-api.us-east-1.amazonaws.com/mock/productos/{idProducto}
