## YAML Template.
---
spring:
    data:
        cassandra:
            keyspacename: pocga
            contactpoints: localhost
            port: 9042
        redis:
            host: localhost
            port: 6379
